### ISSUE TITLE
Python erros

### ISSUE THREAD

**Issue by Lolek1978** [nlohmann/swagger_to_uml#6]
Hi
I tried to run python part of processing calling 

`python swagger_to_uml.py petstore_example/swagger.json >petstore_example/swagger.puml`

and i got message like this
```
  "File "swagger_to_uml.py", line 376
    print(sw.uml, end='', flush=True)"
```

Do you have idea what I'm doing wrong ? :)

Thanks for info :-)

Best regards

**Comment by nlohmann** [comment]
Which Python version are you using? What is the error actual message (your message only indicates a file position)?

**Comment by 5demayo** [comment]
I came across the same issue on MacOSX that uses python version 2 by default. You need to make sure you are running version 3+ by default. After you get past this error you will have to install PyYaml.

**Comment by Lolek1978** [comment]
@nlohmann Sorry, I didn't notice :( - I got exactly this message
```
  File "swagger_to_uml.py", line 376
    print(sw.uml, end='', flush=True)
                     ^
SyntaxError: invalid syntax

```
I use a 2.7.12 version of Python - however I upgrade Python to 3.6 version and i got the same the new error message :-)

```
/opt/repos/swagger_to_uml# python3.6 swagger_to_uml.py petstore_example/swagger.json >petstore_example/swagger.puml
Traceback (most recent call last):
  File "swagger_to_uml.py", line 24, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

I tried to install python-yaml and i got 
```

apt-get install python-yaml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-yaml is already the newest version (3.11-3build1).
0 upgraded, 0 newly installed, 0 to remove and 138 not upgraded.
```
So probably i doing something wrong again :( :]

**Comment by fenollp** [comment]
apt search python3-yaml

**Comment by nlohmann** [comment]
Note you do not need to install all packages globally. This should work:

```
python3 -mvenv venv
venv/bin/pip3 install yaml
venv/bin/python3 swagger_to_uml.py
```

**Comment by Lolek1978** [comment]
@fenollp Thanks ;) for a hint :). It's alive ;).

@nlohmann I tried to call script thats way but i got a lot more of errors ;) - so I stay with @fenollp  sollution :). Thanks for a great job :). I have a fresh new sandbox for swagger conversion ;).
